api_key:
api_base:
model: gpt-4-turbo
temperature: 0
toolbench_url: http://8.218.239.54:8080/rapidapi
tools_folder: "./tools"
cache_folder: "./tool_response_cache"
is_save: true
port: 8080
endpoint: 1 #which one to use from creds.json file
